version: '3.7'

services:
  openapi-gen:
    image: openapitools/openapi-generator-cli
    volumes:
      - ..:/app
    command: generate -g typescript-fetch -i /app/backend/openapi.yaml -o /app/src/backend/generated-rest-client --additional-properties supportsES6=true,typescriptThreePlus=true
